- CHANGELOG.md
- phpstan-baseline.neon
- psalm-baseline.xml
- src/Doctrine/FixtureFactory.php
- test/Doctrine/Fixtures/BasicUsageTest.php
- test/Doctrine/Fixtures/BidirectionalReferencesTest.php
- test/Doctrine/Fixtures/ExtraConfigurationTest.php
- test/Doctrine/Fixtures/IncorrectUsageTest.php
- test/Doctrine/Fixtures/PersistingTest.php
- test/Doctrine/Fixtures/ReferenceTest.php
- test/Doctrine/Fixtures/ReferencesTest.php
- test/Doctrine/Fixtures/SequenceTest.php
- test/Doctrine/Fixtures/SingletonTest.php
- test/Doctrine/Fixtures/TestCase.php
- test/Doctrine/Fixtures/TransitiveReferencesTest.php
This PR
💁‍♂ This should not be necessary since PHP 5.5 and the introduction of the `class` keyword, see https://www.php.net/manual/en/language.oop5.basic.php#language.oop5.basic.class.class.
> Fix: Remove possibility to specify entity namespace

- composer.json
> Fix: Use class-map autoloading for imported classes

- test/AutoReview/SrcCodeTest.php
> Fix: Exclusion

- psalm-baseline.xml
- test/Doctrine/Fixtures/IncorrectUsageTest.php
- test/Doctrine/Fixtures/PersistingTest.php
- test/Doctrine/Fixtures/ReferencesTest.php
- test/Doctrine/ORM/RepositoryTest.php
- test/Doctrine/Types/StatusArrayTest.php
> Fix: Use class keyword

- phpstan-baseline.neon
- psalm-baseline.xml
- test/Doctrine/Fixtures/BasicUsageTest.php
- test/Doctrine/Fixtures/BidirectionalReferencesTest.php
- test/Doctrine/Fixtures/ExtraConfigurationTest.php
- test/Doctrine/Fixtures/IncorrectUsageTest.php
- test/Doctrine/Fixtures/PersistingTest.php
- test/Doctrine/Fixtures/ReferenceTest.php
- test/Doctrine/Fixtures/ReferencesTest.php
- test/Doctrine/Fixtures/SequenceTest.php
- test/Doctrine/Fixtures/SingletonTest.php
- test/Doctrine/Fixtures/TestCase.php
- test/Doctrine/Fixtures/TransitiveReferencesTest.php
This PR
💁‍♂ For reference, see https://stackoverflow.com/q/6453235/1172545.
> Fix: Do not create system under test in setUp()

- phpstan-baseline.neon
- test/Doctrine/Fixtures/BasicUsageTest.php
- test/Doctrine/Fixtures/BidirectionalReferencesTest.php
- test/Doctrine/Fixtures/ExtraConfigurationTest.php
- test/Doctrine/Fixtures/IncorrectUsageTest.php
- test/Doctrine/Fixtures/PersistingTest.php
- test/Doctrine/Fixtures/ReferenceTest.php
- test/Doctrine/Fixtures/ReferencesTest.php
- test/Doctrine/Fixtures/SequenceTest.php
- test/Doctrine/Fixtures/SingletonTest.php
- test/Doctrine/Fixtures/TestCase.php
- test/Doctrine/Fixtures/TransitiveReferencesTest.php
> Fix: Do not create entity manager in setUp()

- CHANGELOG.md
- src/EntityDef.php
- src/FixtureFactory.php
- test/Integration/AbstractTestCase.php
- test/Unit/AbstractTestCase.php
- test/Unit/FixtureFactoryTest.php
> Fix: Use interface in type and return type declarations

- phpstan-baseline.neon
- src/Definition/Definitions.php
- src/Exception/EntityDefinitionUnavailable.php
- src/Exception/Exception.php
- src/Exception/InvalidDefinition.php
- src/Exception/InvalidDirectory.php
- src/FixtureFactory.php
- test/Unit/Definition/DefinitionsTest.php
- test/Unit/Exception/EntityDefinitionUnavailableTest.php
- test/Unit/Exception/InvalidDefinitionTest.php
- test/Unit/Exception/InvalidDirectoryTest.php
- test/Unit/FixtureFactoryTest.php
> Fix: Move exceptions into Exception namespace

- src/Exception/InvalidDefinition.php
- src/Exception/InvalidDirectory.php
> Fix: Implement Exception interface

- src/Exception/Exception.php
> Fix: Remove useless DocBlock

- src/Exception/Exception.php
This PR
💁‍♂ This will allow using `Exception` in `catch` statements.
> Fix: Extend Throwable interface

- .php_cs
- psalm-baseline.xml
- src/EntityDef.php
- src/FieldDef.php
> Fix: Re-enable static_lambda fixer

- .php_cs
> Fix: Remove non-applicable directory exclusion

- test/Fixture/Entity/Artist.php
- test/Fixture/Entity/Badge.php
- test/Fixture/Entity/Commander.php
- test/Fixture/Entity/Name.php
- test/Fixture/Entity/Person.php
- test/Fixture/Entity/Person/User.php
- test/Fixture/Entity/SpaceShip.php
- test/Fixture/Entity/SpaceStation.php
- test/Util/Doctrine/ORM/EntityManagerFactory.php
> Fix: Mapping

- phpstan-baseline.neon
- test/Fixture/Entity/Artist.php
- test/Fixture/Entity/Badge.php
- test/Fixture/Entity/Commander.php
- test/Fixture/Entity/Group.php
- test/Fixture/Entity/Person.php
- test/Fixture/Entity/Person/User.php
- test/Fixture/Entity/SpaceShip.php
- test/Fixture/Entity/SpaceStation.php
- test/Fixture/Entity/User.php
> Fix: Configure mapping for classes used as entities

- .github/workflows/integrate.yaml
- .php_cs
- CHANGELOG.md
- Makefile
- phpstan-baseline.neon
- src/EntityDef.php
- src/FieldDef.php
- src/FixtureFactory.php
- test/Unit/Definition/DefinitionsTest.php
> Fix: Re-enable final_class fixer

- phpstan-baseline.neon
- psalm-baseline.xml
- test/Fixture/FixtureFactory/Entity/Person.php
- test/Fixture/FixtureFactory/Entity/Spaceship.php
- test/Integration/FixtureFactoryTest.php
- test/Unit/FixtureFactoryTest.php
This PR
💁‍♂ For reference, see https://www.merriam-webster.com/dictionary/spaceship.
> Fix: Rename SpaceShip to Spaceship

- test/Unit/FixtureFactoryTest.php
> Fix: Split defining and getting entities

- src/FixtureFactory.php
- test/Integration/FixtureFactoryTest.php
- test/Unit/FixtureFactoryTest.php
> Fix: Whitespace

- phpstan-baseline.neon
- psalm-baseline.xml
- test/Fixture/FixtureFactory/Entity/Badge.php
- test/Fixture/FixtureFactory/Entity/Commander.php
- test/Integration/FixtureFactoryTest.php
- test/Unit/FixtureFactoryTest.php
> Fix: Add inline DocBlocks to assist with type resolution

- psalm-baseline.xml
- test/Integration/FixtureFactoryTest.php
- test/Unit/FixtureFactoryTest.php
> Fix: Rename variables in tests

- test/Unit/Definition/AbstractDefinitionTest.php
> Fix: Avoid FQCNs

- .github/workflows/integrate.yaml
- Makefile
- test/Unit/FixtureFactoryTest.php
> Fix: Consider some indirectly covered classes as covered

- CHANGELOG.md
- src/EntityDef.php
> Fix: Mark class as internal

- src/EntityDef.php
- src/FixtureFactory.php
> Fix: Compose meta data instead of entity manager

- src/EntityDef.php
> Fix: Keep constructor parameters, fields, and assignments in order

- .github/workflows/integrate.yaml
- Makefile
- phpstan-baseline.neon
- psalm-baseline.xml
- src/EntityDef.php
- src/FixtureFactory.php
> Fix: Remove unused accessor, constructor parameter, and field

- phpstan-baseline.neon
- psalm-baseline.xml
- src/EntityDef.php
- src/FixtureFactory.php
> Fix: Remove unnecessary constructor parameter and field

- test/Integration/FixtureFactoryTest.php
> Fix: Remove condition that always evaluates to false

- phpstan-baseline.neon
- psalm-baseline.xml
- src/EntityDef.php
- src/FixtureFactory.php
> Fix: Rename methods, parameters, variables, and fields

- phpstan-baseline.neon
- psalm-baseline.xml
- src/EntityDef.php
- src/FixtureFactory.php
> Fix: Avoid use of isset()

- src/EntityDef.php
- test/Unit/FixtureFactoryTest.php
> Enhancement: Fail early when field definitions reference unavailable fields

- .github/workflows/integrate.yaml
- CHANGELOG.md
- Makefile
- src/EntityDef.php
- test/Unit/FixtureFactoryTest.php
> Fix: Populate referenced embeddables

- test/Fixture/Definition/Definitions/FakerAware/PersonDefinition.php
> Fix: Define Person

- src/FixtureFactory.php
- test/Unit/FixtureFactoryTest.php
> Enhancement: Sort extra fields

- phpstan-baseline.neon
- src/FixtureFactory.php
> Fix: Avoid use of empty()

- CHANGELOG.md
- phpstan-baseline.neon
- psalm-baseline.xml
- src/EntityDef.php
- src/Exception/InvalidFieldNames.php
- src/FixtureFactory.php
- test/Unit/Exception/InvalidFieldNamesTest.php
- test/Unit/FixtureFactoryTest.php
> Enhancement: Throw InvalidFieldNames exception

- test/Unit/FixtureFactoryTest.php
> Fix: Rename test methods

- phpstan-baseline.neon
- psalm-baseline.xml
- src/EntityDef.php
- src/FixtureFactory.php
> Fix: Rename methods

- CHANGELOG.md
- phpstan-baseline.neon
- psalm-baseline.xml
- src/EntityDefinition.php
- src/FixtureFactory.php
- test/AutoReview/SrcCodeTest.php
- test/Unit/Definition/DefinitionsTest.php
- test/Unit/FixtureFactoryTest.php
> Fix: Rename EntityDef to EntityDefinition

- CHANGELOG.md
- phpstan-baseline.neon
- psalm-baseline.xml
- src/FieldDefinition.php
- test/AutoReview/SrcCodeTest.php
- test/Integration/FixtureFactoryTest.php
- test/Unit/FixtureFactoryTest.php
> Fix: Rename FieldDef to FieldDefinition

- phpstan-baseline.neon
- psalm-baseline.xml
- src/EntityDefinition.php
- src/FieldDefinition.php
- src/FixtureFactory.php
> Fix: Add type and return type declarations

- src/EntityDefinition.php
- src/FixtureFactory.php
> Fix: Methods can be static

- phpstan-baseline.neon
- psalm-baseline.xml
- src/EntityDefinition.php
- src/FixtureFactory.php
- test/AutoReview/SrcCodeTest.php
- test/Unit/EntityDefinitionTest.php
- test/Unit/FixtureFactoryTest.php
> Fix: Move operations from EntityDefinition to FixtureFactory

- src/EntityDefinition.php
- src/FixtureFactory.php
- test/Unit/EntityDefinitionTest.php
> Fix: Remove useless accessor

- src/EntityDefinition.php
This PR
Follows #1.
💁‍♂ This brings 
- constructor parameters
- fields
- accessors
in consistent order.
> Fix: Slide method

- CHANGELOG.md
- phpstan-baseline.neon
- psalm-baseline.xml
- src/EntityDefinition.php
- src/FixtureFactory.php
- test/Unit/EntityDefinitionTest.php
- test/Unit/FixtureFactoryTest.php
This PR
Follows #1.
💁‍♂ The `$configuration` only ever handled an `afterCreate` key so far anyway.
> Enhancement: Accept closure instead of array

- test/Unit/FixtureFactoryTest.php
> Fix: Expectation

- CHANGELOG.md
- src/Exception/InvalidCount.php
- src/FieldDefinition.php
- src/FixtureFactory.php
- test/DataProvider/NumberProvider.php
- test/Unit/Exception/InvalidCountTest.php
- test/Unit/FieldDefinitionTest.php
- test/Unit/FixtureFactoryTest.php
> Enhancement: Throw InvalidCount exception

- phpstan-baseline.neon
- src/Exception/EntityDefinitionUnavailable.php
- test/Unit/Exception/EntityDefinitionUnavailableTest.php
> Fix: Extend RuntimeException

- CHANGELOG.md
- src/Exception/EntityDefinitionAlreadyRegistered.php
- src/FixtureFactory.php
- test/Unit/Exception/EntityDefinitionAlreadyRegisteredTest.php
- test/Unit/FixtureFactoryTest.php
> Enhancement: Throw EntityDefinitionAlreadyRegistered exception

- src/Exception/EntityDefinitionNotRegistered.php
- src/FixtureFactory.php
- test/Unit/Exception/EntityDefinitionNotRegisteredTest.php
- test/Unit/FixtureFactoryTest.php
> Fix: Rename exception

- test/Fixture/Definition/Definitions/DoesNotImplementDefinition/RepositoryDefinition.php
- test/Fixture/Definition/Definitions/ImplementsDefinition/RepositoryDefinition.php
- test/Fixture/Definition/Definitions/ImplementsDefinitionButHasPrivateConstructor/RepositoryDefinition.php
- test/Fixture/Definition/Definitions/ImplementsDefinitionButIsAbstract/RepositoryDefinition.php
- test/Fixture/Definition/Definitions/ImplementsDefinitionButThrowsExceptionDuringConstruction/RepositoryDefinition.php
- test/Fixture/Definition/Definitions/ImplementsFakerAwareDefinition/OrganizationDefinition.php
- test/Fixture/Definition/Definitions/ImplementsFakerAwareDefinition/RepositoryDefinition.php
- test/Unit/Definition/DefinitionsTest.php
> Fix: Rename fixture namespaces

- CHANGELOG.md
> Fix: Be more explicit in CHANGELOG

- CHANGELOG.md
- src/Definition/Definition.php
- src/Definition/Definitions.php
- test/Fixture/Definition/Definitions/ImplementsDefinition/RepositoryDefinition.php
- test/Fixture/Definition/Definitions/ImplementsDefinitionButHasPrivateConstructor/RepositoryDefinition.php
- test/Fixture/Definition/Definitions/ImplementsDefinitionButIsAbstract/RepositoryDefinition.php
- test/Fixture/Definition/Definitions/ImplementsDefinitionButThrowsExceptionDuringConstruction/RepositoryDefinition.php
- test/Fixture/Definition/Definitions/ImplementsFakerAwareDefinition/OrganizationDefinition.php
- test/Fixture/Definition/Definitions/ImplementsFakerAwareDefinition/RepositoryDefinition.php
- test/Unit/Definition/DefinitionsTest.php
> Enhancement: Pass in Faker\Generator

- src/FieldDefinition.php
- test/Fixture/Definition/Definitions/DoesNotImplementDefinition/RepositoryDefinition.php
- test/Fixture/Definition/Definitions/ImplementsDefinition/RepositoryDefinition.php
- test/Fixture/Definition/Definitions/ImplementsDefinitionButHasPrivateConstructor/RepositoryDefinition.php
- test/Fixture/Definition/Definitions/ImplementsDefinitionButIsAbstract/RepositoryDefinition.php
- test/Fixture/Definition/Definitions/ImplementsDefinitionButThrowsExceptionDuringConstruction/RepositoryDefinition.php
- test/Fixture/Definition/Definitions/ImplementsFakerAwareDefinition/OrganizationDefinition.php
- test/Fixture/Definition/Definitions/ImplementsFakerAwareDefinition/RepositoryDefinition.php
> Fix: Rename parameter

- CHANGELOG.md
- src/Definition/Definitions.php
- test/Unit/Definition/DefinitionsTest.php
> Fix: Remove provideWith()

- CHANGELOG.md
- src/Exception/ClassNotFound.php
- src/FixtureFactory.php
- test/Unit/Exception/ClassNotFoundTest.php
- test/Unit/FixtureFactoryTest.php
> Enhancement: Throw ClassNotFound exception

- CHANGELOG.md
- src/Exception/ClassMetadataNotFound.php
- src/FixtureFactory.php
- test/Unit/Exception/ClassMetadataNotFoundTest.php
- test/Unit/FixtureFactoryTest.php
> Fix: Throw ClassMetadataNotFound exception

- .github/workflows/integrate.yaml
- Makefile
- test/Unit/FixtureFactoryTest.php
> Fix: Add missing uses annotation

- CHANGELOG.md
- phpstan-baseline.neon
- psalm-baseline.xml
- src/FieldDefinition.php
- src/FixtureFactory.php
> Enhancement: Add template annotations

- psalm-baseline.xml
- src/FixtureFactory.php
This PR
Follows #1.
Blocks #129.
> Fix: Avoid ternary statement

- CHANGELOG.md
- src/FixtureFactory.php
- test/Unit/FixtureFactoryTest.php
> Fix: Do not return FixtureFactory from defineEntity()

- .github/workflows/integrate.yaml
- CHANGELOG.md
- Makefile
- phpstan-baseline.neon
- psalm-baseline.xml
- src/EntityDefinition.php
- src/FixtureFactory.php
This PR
Follows #1.
Related to #129.
> Fix: Remove support for callables that are not closures

- phpstan-baseline.neon
- psalm-baseline.xml
- src/EntityDefinition.php
- src/FieldDefinition.php
- src/FixtureFactory.php
- test/Unit/Definition/DefinitionsTest.php
- test/Unit/EntityDefinitionTest.php
> Enhancement: Turn FieldDefinition into object

- test/Unit/FieldDefinitionTest.php
- test/Unit/FixtureFactoryTest.php
This PR
💁‍♂ Since we have dedicated exceptions now, we don't need to bother with it.
> Fix: Do not bother asserting exception message content

- .github/workflows/integrate.yaml
- Makefile
- test/Unit/FieldDefinitionTest.php
- test/Unit/FixtureFactoryTest.php
> Fix: Add tests for FieldDefinition

- phpstan-baseline.neon
- psalm-baseline.xml
- src/FieldDefinition.php
- src/FixtureFactory.php
- test/Unit/FieldDefinitionTest.php
> Enhancement: Rename __invoke() to resolve()

- .github/workflows/integrate.yaml
> Fix: Wait 5 seconds before merging pull request

- phpstan-baseline.neon
- psalm-baseline.xml
- src/EntityDefinition.php
- src/Exception/InvalidFieldDefinitions.php
- test/Unit/EntityDefinitionTest.php
- test/Unit/Exception/InvalidFieldDefinitionsTest.php
> Fix: Reject invalid field definition values

- src/FixtureFactory.php
> Fix: Wrapping

- psalm-baseline.xml
- test/Unit/FieldDefinitionTest.php
> Fix: Avoid hard-coded expectations

- .github/workflows/integrate.yaml
- CHANGELOG.md
- Makefile
- phpstan-baseline.neon
- psalm-baseline.xml
- src/FieldDefinition.php
- src/FixtureFactory.php
- test/Unit/FieldDefinitionTest.php
> Enhancement: Add FieldDefinition::value()

- CHANGELOG.md
> Fix: Remove extra comma

- src/FixtureFactory.php
> Fix: Remove useless condition

- .github/workflows/integrate.yaml
- CHANGELOG.md
- Makefile
- phpstan-baseline.neon
- psalm-baseline.xml
- src/EntityDefinition.php
- src/FieldDefinition.php
- src/FieldDefinition/Reference.php
- src/FieldDefinition/Resolvable.php
- src/FixtureFactory.php
- test/Integration/FixtureFactoryTest.php
- test/Unit/FieldDefinition/ReferenceTest.php
- test/Unit/FieldDefinitionTest.php
- test/Unit/FixtureFactoryTest.php
> Enhancement: Extract FieldDefinition\Reference

- CHANGELOG.md
- phpstan-baseline.neon
- psalm-baseline.xml
- src/FieldDefinition.php
- src/FieldDefinition/Value.php
- test/DataProvider/ValueProvider.php
- test/Integration/FixtureFactoryTest.php
- test/Unit/Definition/DefinitionsTest.php
- test/Unit/EntityDefinitionTest.php
- test/Unit/FieldDefinition/ReferencesTest.php
- test/Unit/FieldDefinition/ValueTest.php
- test/Unit/FieldDefinitionTest.php
- test/Unit/FixtureFactoryTest.php
> Enhancement: Extract FieldDefinition\Value

- src/Definition.php
- src/Definitions.php
- test/Fixture/Definitions/DoesNotImplementDefinition/RepositoryDefinition.php
- test/Fixture/Definitions/ImplementsDefinition/RepositoryDefinition.php
- test/Fixture/Definitions/ImplementsDefinitionButHasPrivateConstructor/RepositoryDefinition.php
- test/Fixture/Definitions/ImplementsDefinitionButIsAbstract/RepositoryDefinition.php
- test/Fixture/Definitions/ImplementsDefinitionButThrowsExceptionDuringConstruction/RepositoryDefinition.php
- test/Unit/DefinitionsTest.php
> Fix: Move classes into a different namespace

- Makefile
> Fix: Use --generate-baseline to generate baseline

- phpstan-baseline.neon
- psalm-baseline.xml
- src/Definitions.php
- src/EntityDefinition.php
- src/FieldDefinition.php
- src/FieldDefinition/Closure.php
- src/FieldDefinition/Reference.php
- src/FieldDefinition/References.php
- src/FieldDefinition/Resolvable.php
- src/FieldDefinition/Sequence.php
- src/FieldDefinition/Value.php
- src/FixtureFactory.php
> Fix: Use vendor-specific annotations

- CHANGELOG.md
- src/FieldDefinition.php
- src/FixtureFactory.php
- test/Integration/FixtureFactoryTest.php
- test/Unit/EntityDefinitionTest.php
- test/Unit/FieldDefinitionTest.php
- test/Unit/FixtureFactoryTest.php
> Fix: Remove callable support for sequence

- CHANGELOG.md
- phpstan-baseline.neon
- psalm-baseline.xml
- src/FieldDefinition.php
- src/FieldDefinition/Closure.php
- src/FieldDefinition/Reference.php
- src/FieldDefinition/References.php
- src/FieldDefinition/Sequence.php
- src/FieldDefinition/Value.php
- test/Unit/FieldDefinition/ClosureTest.php
- test/Unit/FieldDefinition/ReferenceTest.php
- test/Unit/FieldDefinition/ReferencesTest.php
- test/Unit/FieldDefinition/SequenceTest.php
- test/Unit/FieldDefinition/ValueTest.php
- test/Unit/FieldDefinitionTest.php
> Enhancement: Introduce named constructor and mark primary constructor private

- CHANGELOG.md
- src/FieldDefinition/Reference.php
- src/FixtureFactory.php
- test/Integration/FixtureFactoryTest.php
- test/Unit/FieldDefinition/ClosureTest.php
- test/Unit/FieldDefinitionTest.php
- test/Unit/FixtureFactoryTest.php
> Fix: Rename get() to create()

- CHANGELOG.md
- src/FieldDefinition/References.php
- src/FixtureFactory.php
- test/Unit/FixtureFactoryTest.php
> Fix: Rename getList() to createMultiple()

- phpstan-baseline.neon
- psalm-baseline.xml
- test/Unit/Exception/ClassMetadataNotFoundTest.php
- test/Unit/Exception/ClassNotFoundTest.php
- test/Unit/Exception/EntityDefinitionAlreadyRegisteredTest.php
- test/Unit/Exception/EntityDefinitionNotRegisteredTest.php
- test/Unit/Exception/InvalidCountTest.php
- test/Unit/Exception/InvalidDefinitionTest.php
- test/Unit/Exception/InvalidDirectoryTest.php
- test/Unit/Exception/InvalidFieldDefinitionsTest.php
- test/Unit/Exception/InvalidFieldNamesTest.php
- test/Unit/Exception/InvalidSequenceTest.php
> Fix: Add assertions considered as useless by static code analysis

- .github/workflows/integrate.yaml
- CHANGELOG.md
- Makefile
- src/FieldDefinition.php
- test/Unit/FieldDefinitionTest.php
- test/Unit/FixtureFactoryTest.php
> Fix: Require string sequences to contain %d placeholder

- CHANGELOG.md
- phpstan-baseline.neon
- phpstan.neon
- psalm-baseline.xml
- src/FixtureFactory.php
- test/Double/Faker/FalseGenerator.php
- test/Double/Faker/TrueGenerator.php
- test/Fixture/FixtureFactory/Entity/CodeOfConduct.php
- test/Fixture/FixtureFactory/Entity/Repository.php
- test/Fixture/FixtureFactory/Entity/User.php
- test/Integration/FixtureFactoryTest.php
- test/Unit/DefinitionsTest.php
- test/Unit/FieldDefinition/ClosureTest.php
- test/Unit/FieldDefinition/ReferenceTest.php
- test/Unit/FieldDefinition/ReferencesTest.php
- test/Unit/FieldDefinition/SequenceTest.php
- test/Unit/FieldDefinition/ValueTest.php
- test/Unit/FieldDefinitionTest.php
- test/Unit/FixtureFactoryTest.php
> Enhancement: Resolve optional field definitions randomly

- src/FieldDefinition/Reference.php
- src/FieldDefinition/Sequence.php
> Fix: Remove unnecessary default value

- .github/workflows/integrate.yaml
- CHANGELOG.md
- Makefile
- psalm-baseline.xml
- src/FixtureFactory.php
- test/Unit/FieldDefinitionTest.php
- test/Unit/FixtureFactoryTest.php
This PR
💁‍♂️ This should be resolved differently, for example, by
- allowing to resolve to an exact number of references
- allowing to resolve to a number of references between a minimum and maximum (where the minimum can be set to `0`)
> Fix: Remove FieldDefinition::optionalReferences() and FieldDefinition\References::optional()

- src/FieldDefinition/References.php
> Fix: Space

- .github/workflows/integrate.yaml
- CHANGELOG.md
- Makefile
- phpstan-baseline.neon
- src/Count.php
- src/FieldDefinition.php
- src/FieldDefinition/References.php
- src/FixtureFactory.php
- test/Unit/CountTest.php
- test/Unit/FieldDefinition/ReferencesTest.php
- test/Unit/FieldDefinitionTest.php
- test/Unit/FixtureFactoryTest.php
> Enhancement: Extract Count

- CHANGELOG.md
- src/FieldDefinition/Reference.php
- src/FixtureFactory.php
- test/Integration/FixtureFactoryTest.php
- test/Unit/FieldDefinition/ClosureTest.php
- test/Unit/FieldDefinition/OptionalTest.php
- test/Unit/FieldDefinitionTest.php
- test/Unit/FixtureFactoryTest.php
> Fix: Rename create() to createOne()

- CHANGELOG.md
- phpstan-baseline.neon
- src/FieldDefinition/References.php
- src/FixtureFactory.php
- test/Unit/FixtureFactoryTest.php
> Fix: Rename createMultiple() to createMany()

- CHANGELOG.md
- src/FieldDefinition/References.php
- src/FixtureFactory.php
- test/Unit/FixtureFactoryTest.php
> Fix: Change order of parameters

- test/Unit/FixtureFactoryTest.php
> Fix: Assert that field overrides are used when creating many entities

- src/FixtureFactory.php
> Fix: Add type to DocBlock

- CHANGELOG.md
- src/FixtureFactory.php
- test/Unit/FixtureFactoryTest.php
> Enhancement: Allow using field definitions as overrides

- test/DataProvider/NumberProvider.php
- test/Unit/CountTest.php
- test/Unit/FieldDefinition/ReferencesTest.php
- test/Unit/FieldDefinitionTest.php
- test/Unit/FixtureFactoryTest.php
> Fix: Rename method

- test/DataProvider/NumberProvider.php
- test/Unit/FieldDefinitionTest.php
> Fix: Allow arbitrary integers for sequences

- test/DataProvider/IntProvider.php
- test/Unit/CountTest.php
- test/Unit/FieldDefinition/ReferencesTest.php
- test/Unit/FieldDefinitionTest.php
- test/Unit/FixtureFactoryTest.php
> Fix: Rename data provider

- .github/workflows/integrate.yaml
- CHANGELOG.md
- Makefile
- phpstan-baseline.neon
- psalm-baseline.xml
- src/Exception/InvalidNumber.php
- src/FieldDefinition.php
- src/FieldDefinition/References.php
- src/FixtureFactory.php
- src/Number/Exact.php
- test/Unit/Exception/InvalidNumberTest.php
- test/Unit/FieldDefinition/ReferencesTest.php
- test/Unit/FieldDefinitionTest.php
- test/Unit/FixtureFactoryTest.php
- test/Unit/Number/ExactTest.php
> Fix: Rename Count to Number\Exact

- src/Number/Exact.php
- test/DataProvider/IntProvider.php
- test/Unit/FieldDefinition/ReferencesTest.php
- test/Unit/FieldDefinitionTest.php
- test/Unit/FixtureFactoryTest.php
- test/Unit/Number/ExactTest.php
> Fix: Allow zero as value for Number\Exact

- src/Exception/InvalidNumber.php
- src/Number/Exact.php
- test/Unit/Exception/InvalidNumberTest.php
- test/Unit/Number/ExactTest.php
> Fix: Remove parameter that always has same value and rename method

- test/DataProvider/IntProvider.php
- test/Unit/FixtureFactoryTest.php
> Fix: Usage of faker

- src/FieldDefinition.php
- src/FieldDefinition/References.php
- src/FixtureFactory.php
- src/Number.php
- test/Unit/FieldDefinition/ReferencesTest.php
- test/Unit/FieldDefinitionTest.php
- test/Unit/FixtureFactoryTest.php
- test/Unit/NumberTest.php
This PR
Slightly reverts #273.
> Fix: Rename Number\Exact to Number

- phpstan-baseline.neon
- src/FieldDefinition.php
- src/FixtureFactory.php
- test/Unit/FieldDefinitionTest.php
- test/Unit/FixtureFactoryTest.php
> Fix: Require Number to be passed in

- CHANGELOG.md
- src/Definition.php
- src/Definitions.php
- test/Fixture/Definitions/DoesNotImplementDefinition/RepositoryDefinition.php
- test/Fixture/Definitions/ImplementsDefinition/RepositoryDefinition.php
- test/Fixture/Definitions/ImplementsDefinitionButHasPrivateConstructor/RepositoryDefinition.php
- test/Fixture/Definitions/ImplementsDefinitionButIsAbstract/RepositoryDefinition.php
- test/Fixture/Definitions/ImplementsDefinitionButThrowsExceptionDuringConstruction/RepositoryDefinition.php
- test/Unit/DefinitionsTest.php
> Fix: Remove unneeded parameter

- CHANGELOG.md
- src/FixtureFactory.php
- test/Unit/FixtureFactoryTest.php
> Enhancement: Allow use of faker in closure invoked after entity creation

- src/FixtureFactory.php
> Enhancement: Use array_map()

- src/Definitions.php
> Fix: Verify that class implements interface

- CHANGELOG.md
- src/Definitions.php
- src/Exception/InvalidDefinition.php
- test/Unit/Exception/InvalidDefinitionTest.php
> Fix: Rename named constructor

- CHANGELOG.md
- phpstan-baseline.neon
- psalm-baseline.xml
- src/Definitions.php
- src/Exception/InvalidDefinition.php
- test/Fixture/Definitions/ImplementsDefinitionButCanNotBeInstantiated/OrganizationDefinition.php
- test/Fixture/Definitions/ImplementsDefinitionButCanNotBeInstantiated/RepositoryDefinition.php
- test/Fixture/Definitions/ImplementsDefinitionButCanNotBeInstantiated/UserDefinition.php
- test/Unit/DefinitionsTest.php
- test/Unit/Exception/InvalidDefinitionTest.php
> Fix: Throw InvalidDefinition exception when concrete definition can not be instantiated

- .github/workflows/integrate.yaml
- .php_cs.fixture
- CHANGELOG.md
- Makefile
- phpstan-baseline.neon
- psalm-baseline.xml
- src/Definitions.php
- src/Exception/InvalidDefinition.php
- test/Fixture/Definitions/CanNotBeAutoloaded/OrganizationDefinition.php
- test/Fixture/Definitions/CanNotBeAutoloaded/RepositoryDefinition.php
- test/Fixture/Definitions/CanNotBeAutoloaded/UserDefinition.php
- test/Unit/DefinitionsTest.php
- test/Unit/Exception/InvalidDefinitionTest.php
> Fix: Throw InvalidDefinition exception when definition can not be autoloaded

- src/FixtureFactory.php
> Fix: Expose happy path

- CHANGELOG.md
- src/FixtureFactory.php
- test/Integration/FixtureFactoryTest.php
> Fix: Split persistOnGet()

- test/Integration/FixtureFactoryTest.php
> Fix: Add missing covers annotation

- .github/workflows/integrate.yaml
> Fix: Do not collect coverage

- test/Integration/FixtureFactoryTest.php
> Fix: No need to import faker

- composer.json
- composer.lock
> Fix: Require ramsey/uuid with patch version

- CHANGELOG.md
- src/FixtureFactory.php
- test/Unit/FixtureFactoryTest.php
> Fix: Remove unused method

- README.md
> Fix: Heading level

- CHANGELOG.md
- composer.json
- composer.lock
This PR
💁‍♂️ For reference, see https://github.com/ergebnis/classy/compare/0.5.2...1.0.0.
> Enhancement: Update ergebnis/classy

- example/test/Fixture/Entity/RepositoryDefinitionProvider.php
> Fix: Populate template as optional reference

- test/AutoReview/SrcCodeTest.php
> Fix: Remove exclusion

- CHANGELOG.md
- src/Count.php
- src/FixtureFactory.php
- test/Unit/CountTest.php
> Fix: Move resolution of Count to FixtureFactory

- test/Unit/FixtureFactoryTest.php
> Fix: Turn covers into uses annotation

- test/Unit/FieldDefinitionTest.php
- test/Unit/FixtureFactoryTest.php
> Fix: Signature of closure

- phpstan-baseline.neon
- psalm-baseline.xml
- test/Double/Faker/MaximumGenerator.php
- test/Double/Faker/MinimumGenerator.php
- test/Unit/Strategy/DefaultStrategyTest.php
This PR
Slightly related to #365.
> Fix: Add tests

- .github/workflows/integrate.yaml
- CHANGELOG.md
- Makefile
- README.md
- psalm-baseline.xml
- src/FixtureFactory.php
- src/Strategy/WithOptionalStrategy.php
- test/Unit/FixtureFactory/UsingWithOptionalStrategyTest.php
- test/Unit/Strategy/WithOptionalStrategyTest.php
This PR
💁‍♂️ The fixture factory currently uses a `DefaultStrategy` for resolving field definitions.
This strategy involves random behavior, and
- `FieldDefinition::optionalClosure()` might be resolved to `null` a concrete value
- `FieldDefinition::optionalReference()` might be resolved to `null` or a concrete reference
- `FieldDefinition::optionalSequence()` might be resolved to `null` or a concrete value
- `FieldDefinition::optionalValue()` might be resolved to `null` or a concrete value
- `FieldDefinition::references()` might be resolved to an empty `array` or an `array` of references
You might have a scenario where you have entity definitions that use optional field definitions, but would like to create an entity where these optional field definitions are resolved to concrete values …
> Enhancement: Implement WithOptionalStrategy

- CHANGELOG.md
- README.md
> Enhancement: Implement WithoutOptionalStrategy

- CHANGELOG.md
- phpstan-baseline.neon
- psalm-baseline.xml
- src/FixtureFactory.php
- src/Strategy/WithoutOptionalStrategy.php
- test/Unit/FixtureFactory/UsingWithoutOptionalStrategyTest.php
- test/Unit/FixtureFactoryTest.php
- test/Unit/Strategy/WithoutOptionalStrategyTest.php
This PR
🤦‍♂️ Something went wrong when rebasing in #369.
> Fix: Add WithoutOptionalStrategy

- README.md
> Enhancement: Link to ergebnis/factory-bot-example

- .gitattributes
> Fix: Do not export example/

- .github/dependabot.yml
> Fix: Exclude fakerphp/faker from dependabot updates

- CHANGELOG.md
- composer.json
- composer.lock
> Fix: Require at least doctrine/annotations:^1.10.3

- CHANGELOG.md
- composer.json
- composer.lock
> Fix: Require at least doctrine/collections:^1.6.5

- CHANGELOG.md
- composer.json
- composer.lock
> Fix: Require at least doctrine/orm:^2.8.0

- CHANGELOG.md
- composer.json
- composer.lock
> Fix: Require at least doctrine/dbal:^2.12.0

- composer.json
- composer.lock
> Fix: Do not replace symfony/polyfill-*

- .github/dependabot.yaml
> Fix: Ignore `doctrine/dbal`

- .github/workflows/integrate.yaml
- .github/workflows/renew.yaml
- .php-cs-fixer.fixture.php
- .php-cs-fixer.php
- Makefile
> Fix: Rename `.php_cs` to `.php-cs-fixer.php`

- .php-cs-fixer.fixture.php
> Fix: Do not configure deprecated fixer

- composer.json
- composer.lock
> Fix: Remove `jangregor/phpstan-prophecy`

- example/src/Entity/Organization.php
- example/src/Entity/User.php
> Fix: Use `Collection` interface

- composer.json
- composer.lock
Blocks #697.
Related to https://github.com/doctrine/persistence/pull/122.
> Fix: Require `doctrine/persistence:^2.1.0`

- example/src/Entity/Avatar.php
- example/src/Entity/CodeOfConduct.php
- example/src/Entity/Organization.php
- example/src/Entity/Project.php
- example/src/Entity/Repository.php
- example/src/Entity/User.php
- example/test/Fixture/Entity/OrganizationDefinitionProvider.php
- phpstan-baseline.neon
- src/Count.php
- src/EntityDefinition.php
- src/FieldDefinition/Closure.php
- src/FieldDefinition/Optional.php
- src/FieldDefinition/Reference.php
- src/FieldDefinition/References.php
- src/FieldDefinition/Sequence.php
- src/FixtureFactory.php
> Fix: Add property type declarations

- example/test/Fixture/Entity/CodeOfConductDefinitionProvider.php
- example/test/Fixture/Entity/OrganizationDefinitionProvider.php
- example/test/Fixture/Entity/ProjectDefinitionProvider.php
- example/test/Fixture/Entity/RepositoryDefinitionProvider.php
- example/test/Fixture/Entity/UserDefinitionProvider.php
- psalm-baseline.xml
- test/DataProvider/ValueProvider.php
- test/Integration/FixtureFactoryTest.php
- test/Unit/Exception/InvalidFieldNamesTest.php
- test/Unit/FieldDefinition/SequenceTest.php
- test/Unit/FieldDefinitionTest.php
- test/Unit/FixtureFactoryTest.php
> Fix: Use methods instead of deprecated magic properties

- CHANGELOG.md
- README.md
- phpstan-baseline.neon
- psalm-baseline.xml
- src/FieldDefinition.php
- src/FieldDefinition/Reference.php
- src/FieldDefinition/References.php
- test/Unit/FieldDefinition/ReferenceTest.php
- test/Unit/FieldDefinition/ReferencesTest.php
- test/Unit/FieldDefinitionTest.php
This PR allows users to override the default field definitions when referencing an entity in the FixtureFactory.
Resolves #418.
> Allow field definitions to be overridden when using reference.

- CHANGELOG.md
- README.md
- phpstan-baseline.neon
- src/FixtureFactory.php
- test/Unit/FixtureFactoryTest.php
> Enhancement: Allow registering already instantiated entity definition providers

- .github/dependabot.yaml
> Fix: Do not let dependabot update `doctrine/persistence`

- composer.json
- composer.lock
> Fix: Require `ext-pdo_sqlite`

- example/src/Entity/Avatar.php
- example/src/Entity/CodeOfConduct.php
- example/src/Entity/Organization.php
- example/src/Entity/Project.php
- example/src/Entity/Repository.php
- example/src/Entity/User.php
- example/test/Unit/AbstractTestCase.php
- phpstan-baseline.neon
- psalm-baseline.xml
- rector.php
- test/Util/Doctrine/ORM/EntityManagerFactory.php
> Enhancement: Use attributes

- CHANGELOG.md
- composer.json
- composer.lock
> Fix: Remove `doctrine/annotations`

- .github/CONTRIBUTING.md
- .github/dependabot.yaml
- .github/settings.yml
- .github/workflows/integrate.yaml
- .github/workflows/release.yaml
- .github/workflows/renew.yaml
- .php-cs-fixer.php
- Makefile
- psalm-baseline.xml
> Enhancement: Synchronize with `ergebnis/php-package-template`

- CHANGELOG.md
- composer.json
- composer.lock
Blocks #1295.
Related to #1293.
> Fix: Require `doctrine/orm:^2.12.0`

- CHANGELOG.md
- composer.json
- composer.lock
Blocks #1295.
Related to #1297.
> Fix: Require `doctrine/orm:^2.14.0`

- example/test/Unit/AbstractTestCase.php
- phpstan-baseline.neon
- psalm-baseline.xml
- test/Util/Doctrine/ORM/EntityManagerFactory.php
> Fix: Do not use deprecated `Doctrine\ORM\EntityManager::create()`

- psalm-baseline.xml
- src/FieldResolution/DefaultStrategy.php
- src/FieldResolution/ResolutionStrategy.php
- src/FieldResolution/WithOptionalStrategy.php
- src/FieldResolution/WithoutOptionalStrategy.php
- src/FixtureFactory.php
- test/Integration/FixtureFactoryTest.php
- test/Unit/FieldDefinition/ClosureTest.php
- test/Unit/FieldDefinition/OptionalTest.php
- test/Unit/FieldDefinition/ReferenceTest.php
- test/Unit/FieldDefinition/ReferencesTest.php
- test/Unit/FieldResolution/DefaultStrategyTest.php
- test/Unit/FieldResolution/WithOptionalStrategyTest.php
- test/Unit/FieldResolution/WithoutOptionalStrategyTest.php
- test/Unit/FixtureFactory/UsingDefaultStrategyTest.php
- test/Unit/FixtureFactory/UsingWithOptionalStrategyTest.php
- test/Unit/FixtureFactory/UsingWithoutOptionalStrategyTest.php
- test/Unit/FixtureFactoryTest.php
> Fix: Move classes

- src/FieldResolution/FieldValueResolutionStrategy.php
- src/FieldResolution/ResolutionStrategy.php
- src/FieldResolution/WithOptionalStrategy.php
- src/FieldResolution/WithoutOptionalStrategy.php
- src/FixtureFactory.php
> Enhancement: Extract `FieldValueResolutionStrategy` interface

- src/FieldResolution/CountResolutionStrategy.php
- src/FieldResolution/DefaultStrategy.php
- src/FieldResolution/WithOptionalStrategy.php
- src/FieldResolution/WithoutOptionalStrategy.php
- src/FixtureFactory.php
> Fix: Rename `ResolutionStrategy` to `CountResolutionStrategy`

- phpstan-baseline.neon
- psalm-baseline.xml
- src/EntityDefinition.php
- src/FixtureFactory.php
- test/Unit/EntityDefinitionTest.php
> Enhancement: Extract named constructor

- CHANGELOG.md
- composer.json
- composer.lock
- phpstan-baseline.neon
- src/FixtureFactory.php
> Enhancement: Require and use `doctrine/instantiator` directly
