ergebnis/factory-bot

- .gitattributes
- .github/workflows/integrate.yaml
- Makefile
- config/cli-config.php
- test/Integration/AbstractTestCase.php
- test/Util/Doctrine/ORM/EntityManagerFactory.php
> Enhancement: Show and validate Doctrine mapping information

- test/Fixture/Entity/Artist.php
- test/Fixture/Entity/Badge.php
- test/Fixture/Entity/Commander.php
- test/Fixture/Entity/Name.php
- test/Fixture/Entity/Person.php
- test/Fixture/Entity/Person/User.php
- test/Fixture/Entity/SpaceShip.php
- test/Fixture/Entity/SpaceStation.php
This PR
Related to https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4803.
Blocks #33.
> Fix: Use alias for now

- composer.json
- composer.lock
- config/object-manager.php
- phpstan-baseline.neon
- phpstan.neon
- psalm-baseline.xml
- test/Fixture/FixtureFactory/Entity/Artist.php
- test/Fixture/FixtureFactory/Entity/Badge.php
- test/Fixture/FixtureFactory/Entity/Commander.php
- test/Fixture/FixtureFactory/Entity/Person.php
- test/Fixture/FixtureFactory/Entity/SpaceStation.php
- test/Fixture/FixtureFactory/Entity/Spaceship.php
> Enhancement: Require and use phpstan/phpstan-doctrine

- .github/workflows/integrate.yaml
- Makefile
- test/Unit/FixtureFactoryTest.php
> Fix: Assert exception messages

- src/EntityDef.php
> Fix: Invert condition to expose happy path

- psalm-baseline.xml
- src/EntityDef.php
- src/FixtureFactory.php
> Enhancement: Assemble exception messages using sprintf()

- .editorconfig
- .github/workflows/integrate.yaml
- Makefile
- phpstan.neon
> Enhancement: Synchronize with ergebnis/php-library-template

- phpstan-baseline.neon
- psalm-baseline.xml
- src/FixtureFactory.php
- test/Unit/FixtureFactoryTest.php
> Fix: Add more tests for FixtureFactory::defineEntity()

- src/EntityDef.php
> Fix: Inline method

- src/EntityDef.php
> Fix: Continue early

- .github/workflows/integrate.yaml
- Makefile
- psalm-baseline.xml
- src/FixtureFactory.php
> Fix: Simplify constructor

- test/Unit/FixtureFactoryTest.php
> Fix: Assert exception message

- phpstan-baseline.neon
- psalm-baseline.xml
- src/FixtureFactory.php
This PR
Follows #1.
Follows #93.
🤦‍♂
> Fix: Add return type declaration

- psalm-baseline.xml
- src/FixtureFactory.php
This PR
Follows #1.
Follows #93.
🤦‍♂
> Fix: Add type declaration

- phpstan-baseline.neon
- psalm-baseline.xml
- src/EntityDefinition.php
- src/FixtureFactory.php
> Fix: DocBlocks

- psalm-baseline.xml
- test/Unit/FixtureFactoryTest.php
> Fix: Remove bad code example

- src/Exception/EntityDefinitionUnavailable.php
- src/FieldDefinition.php
- src/FixtureFactory.php
- test/Unit/Exception/EntityDefinitionUnavailableTest.php
> Fix: Rename parameter

- .github/workflows/integrate.yaml
> Fix: Bring back Doctrine checks

- CHANGELOG.md
> Fix: Move items into Removed section

- src/Definition/Definition.php
- test/Fixture/Definition/Definitions/DoesNotImplementDefinition/RepositoryDefinition.php
This PR
Follows #117 and #118.
> Fix: Signature

- test/DataProvider/NumberProvider.php
- test/Unit/FieldDefinitionTest.php
- test/Unit/FixtureFactoryTest.php
> Fix: Reduce number of values

- test/Integration/AbstractTestCase.php
- test/Integration/FixtureFactoryTest.php
- test/Unit/AbstractTestCase.php
- test/Unit/Definition/DefinitionsTest.php
- test/Unit/FieldDefinitionTest.php
- test/Unit/FixtureFactoryTest.php
> Fix: Rename method

- CHANGELOG.md
- src/FieldDefinition.php
- test/Fixture/FixtureFactory/Entity/User.php
- test/Unit/FieldDefinitionTest.php
> Enhancement: Add FieldDefinition::closure()

- .github/workflows/integrate.yaml
- CHANGELOG.md
- Makefile
- phpstan-baseline.neon
- psalm-baseline.xml
- src/FieldDefinition.php
- src/FieldDefinition/References.php
- test/Unit/FieldDefinition/ReferencesTest.php
- test/Unit/FieldDefinitionTest.php
- test/Unit/FixtureFactoryTest.php
> Enhancement: Extract FieldDefinition\References

- CHANGELOG.md
- phpstan-baseline.neon
- psalm-baseline.xml
- src/FieldDefinition.php
- src/FieldDefinition/Closure.php
- test/Unit/FieldDefinition/ClosureTest.php
- test/Unit/FieldDefinitionTest.php
> Enhancement: Extract FieldDefinition\Closure

- phpstan-baseline.neon
- psalm-baseline.xml
- src/FieldDefinition.php
> Fix: Combine cases

- test/Integration/AbstractTestCase.php
- test/Integration/FixtureFactoryTest.php
- test/Unit/AbstractTestCase.php
- test/Unit/Definition/DefinitionsTest.php
- test/Unit/FieldDefinitionTest.php
- test/Unit/FixtureFactoryTest.php
> Fix: Pull up import into AbstractTestCase

- psalm-baseline.xml
- src/FixtureFactory.php
> Fix: Return early

- test/Fixture/FixtureFactory/Entity/Avatar.php
- test/Fixture/FixtureFactory/Entity/Organization.php
- test/Fixture/FixtureFactory/Entity/Project.php
- test/Fixture/FixtureFactory/Entity/Repository.php
- test/Fixture/FixtureFactory/Entity/User.php
> Fix: Avoid using aliases

- test/Fixture/FixtureFactory/Entity/Organization.php
- test/Fixture/FixtureFactory/Entity/User.php
> Fix: Import

- phpstan-baseline.neon
- psalm-baseline.xml
- test/Unit/FieldDefinitionTest.php
> Fix: Simplify tests

- src/FieldDefinition.php
> Fix: Sort methods

- test/Unit/FixtureFactoryTest.php
> Fix: Add tests asserting what field definitions resolve to

- .github/workflows/integrate.yaml
- CHANGELOG.md
- Makefile
- phpstan-baseline.neon
- psalm-baseline.xml
- src/FieldDefinition.php
- src/FieldDefinition/Closure.php
- src/FieldDefinition/Reference.php
- src/FieldDefinition/References.php
- src/FieldDefinition/Resolvable.php
- src/FieldDefinition/Sequence.php
- src/FieldDefinition/Value.php
- test/Unit/FieldDefinition/ClosureTest.php
- test/Unit/FieldDefinition/ReferenceTest.php
- test/Unit/FieldDefinition/ReferencesTest.php
- test/Unit/FieldDefinition/SequenceTest.php
- test/Unit/FieldDefinition/ValueTest.php
- test/Unit/FieldDefinitionTest.php
> Enhancement: Allow optional field definitions

- phpstan-baseline.neon
- src/Exception/InvalidFieldDefinitions.php
- test/Unit/Exception/InvalidFieldDefinitionsTest.php
> Fix: Extend InvalidArgumentException

- test/Fixture/FixtureFactory/Entity/Organization.php
> Fix: Table name

- .github/dependabot.yml
> Fix: Restore ignore rules

- src/FieldDefinition.php
> Fix: Add type declarations

- .github/workflows/integrate.yaml
- CHANGELOG.md
- Makefile
- phpstan-baseline.neon
- psalm-baseline.xml
- src/FieldDefinition.php
- src/FieldDefinition/Optional.php
- src/FieldDefinition/Reference.php
- src/FieldDefinition/References.php
- src/FieldDefinition/Resolvable.php
- src/FieldDefinition/Sequence.php
- src/FieldDefinition/Value.php
- src/FixtureFactory.php
- test/Unit/FieldDefinition/OptionalTest.php
- test/Unit/FieldDefinition/ReferenceTest.php
- test/Unit/FieldDefinition/ReferencesTest.php
- test/Unit/FieldDefinition/SequenceTest.php
- test/Unit/FieldDefinition/ValueTest.php
- test/Unit/FieldDefinitionTest.php
- test/Unit/FixtureFactoryTest.php
> Enhancement: Extract FieldDefinition\Optional

- src/FixtureFactory.php
> Fix: Space

- test/Unit/FixtureFactoryTest.php
> Fix: Add test

- psalm-baseline.xml
- src/FixtureFactory.php
> Fix: Add DocBlock

- .github/workflows/integrate.yaml
- CHANGELOG.md
- Makefile
- src/FieldDefinition/Closure.php
- src/FieldDefinition/Optional.php
- src/FieldDefinition/Reference.php
- src/FieldDefinition/References.php
- src/FieldDefinition/Resolvable.php
- src/FieldDefinition/Sequence.php
- src/FieldDefinition/Value.php
- src/FixtureFactory.php
- test/Unit/FieldDefinition/ClosureTest.php
- test/Unit/FieldDefinition/OptionalTest.php
- test/Unit/FieldDefinition/ReferenceTest.php
- test/Unit/FieldDefinition/ReferencesTest.php
- test/Unit/FieldDefinition/SequenceTest.php
- test/Unit/FieldDefinition/ValueTest.php
- test/Unit/FixtureFactoryTest.php
> Enhancement: Allow use of faker in field definitions

- .github/workflows/integrate.yaml
- Makefile
- phpstan-baseline.neon
- psalm-baseline.xml
- src/Exception/InvalidMaximum.php
- src/Exception/InvalidMinimum.php
- src/FieldDefinition.php
- src/FixtureFactory.php
- src/Number.php
- test/DataProvider/IntProvider.php
- test/Double/Faker/FalseGenerator.php
- test/Double/Faker/TrueGenerator.php
- test/Unit/Exception/InvalidMaximumTest.php
- test/Unit/Exception/InvalidMinimumTest.php
- test/Unit/FieldDefinition/ReferencesTest.php
- test/Unit/FieldDefinitionTest.php
- test/Unit/FixtureFactoryTest.php
- test/Unit/NumberTest.php
> Enhancement: Allow creation of Number from minimum and maximum values

- test/Unit/FixtureFactoryTest.php
> Fix: Add missing test

- .github/settings.yml
- composer.json
> Enhancement: Add keywords

- test/Unit/FixtureFactoryTest.php
> Fix: Flaky test

- .github/workflows/integrate.yaml
- Makefile
> Fix: Mutation score indicator

- .github/settings.yml
- README.md
> Fix: Description

- .github/workflows/integrate.yaml
- Makefile
- test/Fixture/Definitions/DoesNotImplementDefinition/OrganizationDefinition.php
- test/Fixture/Definitions/DoesNotImplementDefinition/UserDefinition.php
- test/Fixture/Definitions/ImplementsDefinition/OrganizationDefinition.php
- test/Fixture/Definitions/ImplementsDefinition/UserDefinition.php
- test/Fixture/Definitions/ImplementsDefinitionButHasPrivateConstructor/OrganizationDefinition.php
- test/Fixture/Definitions/ImplementsDefinitionButHasPrivateConstructor/UserDefinition.php
- test/Fixture/Definitions/ImplementsDefinitionButIsAbstract/OrganizationDefinition.php
- test/Fixture/Definitions/ImplementsDefinitionButIsAbstract/UserDefinition.php
- test/Fixture/Definitions/ImplementsDefinitionButThrowsExceptionDuringConstruction/OrganizationDefinition.php
- test/Fixture/Definitions/ImplementsDefinitionButThrowsExceptionDuringConstruction/UserDefinition.php
- test/Unit/DefinitionsTest.php
> Fix: Improve tests for Definitions

- src/Definitions.php
> Fix: Split condition

- .github/workflows/integrate.yaml
- Makefile
- test/Unit/NumberTest.php
> Fix: Improve tests for Number

- psalm-baseline.xml
- src/FixtureFactory.php
> Fix: Use array_map()

- CHANGELOG.md
- phpstan-baseline.neon
- psalm-baseline.xml
- src/Count.php
- src/Exception/InvalidCount.php
- src/FieldDefinition.php
- src/FieldDefinition/References.php
- src/FixtureFactory.php
- test/Unit/CountTest.php
- test/Unit/Exception/InvalidCountTest.php
- test/Unit/FieldDefinition/ReferencesTest.php
- test/Unit/FieldDefinitionTest.php
- test/Unit/FixtureFactoryTest.php
> Fix: Rename Number to Count

- test/Integration/FixtureFactoryTest.php
> Fix: Add tests for persistOnGet()

- .php_cs.fixture
- CHANGELOG.md
- src/EntityDefinitionProvider.php
- src/FixtureFactory.php
- test/Fixture/DefinitionProvider/CanNotBeAutoloaded/OrganizationDefinitionProvider.php
- test/Fixture/DefinitionProvider/CanNotBeAutoloaded/RepositoryDefinitionProvider.php
- test/Fixture/DefinitionProvider/CanNotBeAutoloaded/UserDefinitionProvider.php
- test/Fixture/DefinitionProvider/DoesNotImplementDefinitionProvider/OrganizationDefinitionProvider.php
- test/Fixture/DefinitionProvider/DoesNotImplementDefinitionProvider/RepositoryDefinition.php
- test/Fixture/DefinitionProvider/DoesNotImplementDefinitionProvider/UserDefinitionProvider.php
- test/Fixture/DefinitionProvider/ImplementsDefinitionProvider/OrganizationDefinitionProvider.php
- test/Fixture/DefinitionProvider/ImplementsDefinitionProvider/RepositoryDefinitionProvider.php
- test/Fixture/DefinitionProvider/ImplementsDefinitionProvider/UserDefinitionProvider.php
- test/Fixture/DefinitionProvider/ImplementsDefinitionProviderButCanNotBeInstantiated/OrganizationDefinitionProvider.php
- test/Fixture/DefinitionProvider/ImplementsDefinitionProviderButCanNotBeInstantiated/RepositoryDefinitionProvider.php
- test/Fixture/DefinitionProvider/ImplementsDefinitionProviderButCanNotBeInstantiated/UserDefinitionProvider.php
- test/Fixture/DefinitionProvider/ImplementsDefinitionProviderButIsAbstract/OrganizationDefinitionProvider.php
- test/Fixture/DefinitionProvider/ImplementsDefinitionProviderButIsAbstract/RepositoryDefinitionProvider.php
- test/Fixture/DefinitionProvider/ImplementsDefinitionProviderButIsAbstract/UserDefinitionProvider.php
- test/Fixture/DefinitionProvider/ImplementsDefinitionProviderButThrowsExceptionDuringInstantiation/OrganizationDefinitionProvider.php
- test/Fixture/DefinitionProvider/ImplementsDefinitionProviderButThrowsExceptionDuringInstantiation/RepositoryDefinitionProvider.php
- test/Fixture/DefinitionProvider/ImplementsDefinitionProviderButThrowsExceptionDuringInstantiation/UserDefinitionProvider.php
- test/Unit/FixtureFactoryTest.php
> Fix: Rename Definition to EntityDefinitionProvider

- test/Fixture/DefinitionProvider/CanNotBeAutoloaded/OrganizationDefinitionProvider.php
- test/Fixture/DefinitionProvider/CanNotBeAutoloaded/RepositoryDefinitionProvider.php
- test/Fixture/DefinitionProvider/CanNotBeAutoloaded/UserDefinitionProvider.php
- test/Fixture/DefinitionProvider/DoesNotImplementDefinitionProvider/OrganizationDefinitionProvider.php
- test/Fixture/DefinitionProvider/DoesNotImplementDefinitionProvider/RepositoryDefinition.php
- test/Fixture/DefinitionProvider/DoesNotImplementDefinitionProvider/UserDefinitionProvider.php
- test/Fixture/DefinitionProvider/ImplementsDefinitionProviderButCanNotBeInstantiated/OrganizationDefinitionProvider.php
- test/Fixture/DefinitionProvider/ImplementsDefinitionProviderButCanNotBeInstantiated/RepositoryDefinitionProvider.php
- test/Fixture/DefinitionProvider/ImplementsDefinitionProviderButCanNotBeInstantiated/UserDefinitionProvider.php
- test/Fixture/DefinitionProvider/ImplementsDefinitionProviderButIsAbstract/OrganizationDefinitionProvider.php
- test/Fixture/DefinitionProvider/ImplementsDefinitionProviderButIsAbstract/RepositoryDefinitionProvider.php
- test/Fixture/DefinitionProvider/ImplementsDefinitionProviderButIsAbstract/UserDefinitionProvider.php
- test/Fixture/DefinitionProvider/ImplementsDefinitionProviderButThrowsExceptionDuringInstantiation/OrganizationDefinitionProvider.php
- test/Fixture/DefinitionProvider/ImplementsDefinitionProviderButThrowsExceptionDuringInstantiation/RepositoryDefinitionProvider.php
- test/Fixture/DefinitionProvider/ImplementsDefinitionProviderButThrowsExceptionDuringInstantiation/UserDefinitionProvider.php
> Fix: Do not import every single class

- .github/workflows/integrate.yaml
- Makefile
- composer.json
- composer.lock
- example/src/Entity/Organization.php
- example/src/Entity/Project.php
- example/src/Entity/Repository.php
- example/src/Entity/User.php
- example/test/AutoReview/FixtureTest.php
- example/test/AutoReview/phpunit.xml
- example/test/Fixture/Entity/AvatarDefinitionProvider.php
- example/test/Fixture/Entity/CodeOfConductDefinitionProvider.php
- example/test/Fixture/Entity/ProjectDefinitionProvider.php
- example/test/Fixture/Entity/RepositoryDefinitionProvider.php
- example/test/Fixture/Entity/UserDefinitionProvider.php
- example/test/Unit/AbstractTestCase.php
- example/test/Unit/Entity/UserTest.php
- example/test/Unit/phpunit.xml
- phpstan-baseline.neon
- phpstan.neon
- psalm-baseline.xml
- test/Integration/FixtureFactoryTest.php
- test/Unit/FixtureFactoryTest.php
> Enhancement: Add examples and example tests

- CHANGELOG.md
- src/FixtureFactory.php
- src/Persistence/NonPersistingStrategy.php
- src/Persistence/PersistenceStrategy.php
- src/Persistence/PersistingStrategy.php
- test/Integration/FixtureFactoryTest.php
- test/Unit/FieldDefinition/ClosureTest.php
- test/Unit/FieldDefinition/OptionalTest.php
- test/Unit/FieldDefinition/ReferenceTest.php
- test/Unit/FieldDefinition/ReferencesTest.php
- test/Unit/FieldDefinition/SequenceTest.php
- test/Unit/FieldDefinition/ValueTest.php
- test/Unit/FixtureFactoryTest.php
- test/Unit/Persistence/NonPersistingStrategyTest.php
- test/Unit/Persistence/PersistingStrategyTest.php
> Enhancement: Extract persisting strategies

- CHANGELOG.md
- psalm-baseline.xml
- src/FieldValue/DefaultResolutionStrategy.php
- src/FieldValue/ResolutionStrategy.php
- src/FixtureFactory.php
- test/Integration/FixtureFactoryTest.php
- test/Unit/FieldDefinition/ClosureTest.php
- test/Unit/FieldDefinition/OptionalTest.php
- test/Unit/FieldDefinition/ReferenceTest.php
- test/Unit/FieldDefinition/ReferencesTest.php
- test/Unit/FieldValue/DefaultResolutionStrategyTest.php
- test/Unit/FixtureFactoryTest.php
> Enhancement: Extract field value resolution strategy

- .gitattributes
- README.md
> Enhancement: Add documentation

- README.md
> Enhancement: Add headings

- README.md
> Fix: Remove double space

- README.md
> Fix: Add documentation for closure invoked after creation

- test/Unit/Persistence/NonPersistingStrategyTest.php
- test/Unit/Persistence/PersistingStrategyTest.php
> Fix: Order

- src/FieldValue/DefaultResolutionStrategy.php
- src/FieldValue/ResolutionStrategy.php
- src/Persistence/NonPersistingStrategy.php
- src/Persistence/PersistenceStrategy.php
- src/Persistence/PersistingStrategy.php
> Fix: Mark strategies as internal

- CHANGELOG.md
- psalm-baseline.xml
- src/FixtureFactory.php
- src/Strategy/DefaultStrategy.php
- src/Strategy/ResolutionStrategy.php
- test/AutoReview/SrcCodeTest.php
- test/Integration/FixtureFactoryTest.php
- test/Unit/FieldDefinition/ClosureTest.php
- test/Unit/FieldDefinition/OptionalTest.php
- test/Unit/FieldDefinition/ReferenceTest.php
- test/Unit/FieldDefinition/ReferencesTest.php
- test/Unit/FixtureFactoryTest.php
- test/Unit/Strategy/DefaultStrategyTest.php
> Enhancement: Extract DefaultStrategy

- README.md
> Fix: Usage example

- test/Unit/FixtureFactory/UsingDefaultStrategyTest.php
> Fix: Remove duplicate tests

- test/Unit/Strategy/DefaultStrategyTest.php
This PR
Slightly related to #365.
> Fix: Add tests

- test/Unit/FieldDefinitionTest.php
- test/Unit/FixtureFactory/UsingDefaultStrategyTest.php
- test/Unit/FixtureFactory/UsingWithOptionalStrategyTest.php
> Fix: Method names

- CHANGELOG.md
- README.md
- phpstan-baseline.neon
- psalm-baseline.xml
- src/FixtureFactory.php
- test/Integration/FixtureFactoryTest.php
- test/Unit/FixtureFactoryTest.php
> Enhancement: Replace persistAfterCreate() and doNotPersistAfterCreate() with persisting()

- CHANGELOG.md
- composer.json
- composer.lock
> Fix: Use fakerphp/faker instead of fzaninotto/faker

- .github/settings.yml
- .github/workflows/integrate.yaml
- .php_cs
- .php_cs.fixture
- CHANGELOG.md
- composer.json
- composer.lock
> Fix: Drop support for PHP 7.2

- psalm-baseline.xml
> Fix: Run 'make static-code-analysis-baseline'

- composer.json
- composer.lock
This PR
* Removes unnecessary polyfills 
Fixes #515
> Remove unnecessary polyfills

- composer.json
- composer.lock
> Fix: Require symfony/cache

- .github/dependabot.yaml
> Fix: Remove unnecessary version configuration

- composer.json
- composer.lock
> Fix: Require `composer/package-versions-deprecated`

- composer.json
- composer.lock
> Fix: Remove `composer/package-versions-deprecated`

- .php-cs-fixer.fixture.php
- .php-cs-fixer.php
> Enhancement: Use `Php74` rule set

- composer.json
> Fix: Allow composer plugin

- phpstan-baseline.neon
- psalm-baseline.xml
- test/DataProvider/IntProvider.php
- test/DataProvider/ValueProvider.php
- test/Integration/AbstractTestCase.php
- test/Unit/AbstractTestCase.php
- test/Unit/CountTest.php
- test/Unit/EntityDefinitionTest.php
- test/Unit/Exception/InvalidCountTest.php
- test/Unit/Exception/InvalidDefinitionTest.php
- test/Unit/Exception/InvalidDirectoryTest.php
- test/Unit/Exception/InvalidFieldDefinitionsTest.php
- test/Unit/Exception/InvalidFieldNamesTest.php
- test/Unit/Exception/InvalidMaximumTest.php
- test/Unit/Exception/InvalidMinimumTest.php
- test/Unit/Exception/InvalidSequenceTest.php
- test/Util/Helper.php
> Enhancement: Pull in `Helper` from `ergebnis/test-util`

- CHANGELOG.md
- composer.json
- composer.lock
Follows https://twitter.com/greg0ire/status/1575487426692526088?s=46&t=HMorSArZfN_Yp4xfKyyypw
There shouldn't be any BC breaks
> Allow `doctrine/collections` 2

- .github/settings.yml
- .github/workflows/integrate.yaml
- .github/workflows/renew.yaml
- CHANGELOG.md
> Fix: Drop support for PHP 7.4

- CHANGELOG.md
- composer.json
- composer.lock
- psalm-baseline.xml
💁‍♂️ For reference, see https://github.com/FakerPHP/Faker/compare/v1.16.0...v1.21.0.
> Enhancement: Update `fakerphp/faker`

- CHANGELOG.md
- composer.json
- composer.lock
> Enhancement: Allow installation of `doctrine/persistence:^3.0.0`

- CHANGELOG.md
- composer.json
- composer.lock
> Enhancement: Allow installation of `doctrine/annotations:^2.0.0`

- .github/CODEOWNERS
- .github/CONTRIBUTING.md
- .github/SECURITY.md
- .github/settings.yml
- .github/workflows/integrate.yaml
- .github/workflows/renew.yaml
- .gitignore
- .php-cs-fixer.php
- .yamllint.yaml
- Makefile
- README.md
- composer-require-checker.json
- rector.php
> Enhancement: Synchronize with `ergebnis/php-package-template`

- .github/settings.yml
- .github/workflows/integrate.yaml
- .github/workflows/renew.yaml
- .php-cs-fixer.fixture.php
- .php-cs-fixer.php
- CHANGELOG.md
- composer.json
- composer.lock
- rector.php
> Fix: Drop support for PHP 8.0

- CHANGELOG.md
- composer.json
- composer.lock
- phpstan-baseline.neon
- psalm-baseline.xml
> Enhancement: Require `doctrine/orm:^2.9.0`

- .github/workflows/integrate.yaml
- .php-cs-fixer.php
- Makefile
- bin/console
- phpstan.neon
- psalm.xml
Blocks #1293.
💁‍♂️ For reference, see https://www.doctrine-project.org/projects/doctrine-orm/en/2.19/reference/tools.html#setting-up-the-console.
> Enhancement: Implement `console` script

- CHANGELOG.md
- composer-require-checker.json
- composer.json
- composer.lock
- phpstan-baseline.neon
- psalm-baseline.xml
- src/FixtureFactory.php
> Enhancement: Allow installation of `doctrine/orm:^3.0.0`

- src/FieldResolution/MinimumCountResolutionStrategy.php
- src/FieldResolution/WithoutOptionalStrategy.php
- src/FixtureFactory.php
- test/Unit/FieldResolution/MinimumCountResolutionStrategyTest.php
- test/Unit/FieldResolution/WithoutOptionalStrategyTest.php
- test/Unit/FixtureFactory/UsingWithoutOptionalStrategyTest.php
> Enhancement: Extract `MinimumCountResolutionStrategy`

- psalm-baseline.xml
- src/FieldResolution/CountResolution/BetweenMinimumAndMaximumCount.php
- src/FieldResolution/CountResolution/BetweenMinimumAndMaximumGreaterThanZeroCount.php
- src/FieldResolution/CountResolution/CountResolutionStrategy.php
- src/FieldResolution/CountResolution/MinimumCount.php
- src/FieldResolution/FieldValueResolution/FieldValueResolutionStrategy.php
- src/FieldResolution/FieldValueResolution/WithOptionalFieldValue.php
- src/FieldResolution/FieldValueResolution/WithOrWithoutOptionalFieldValue.php
- src/FieldResolution/FieldValueResolution/WithoutOptionalFieldValue.php
- src/FixtureFactory.php
- test/Integration/FixtureFactoryTest.php
- test/Unit/FieldDefinition/ClosureTest.php
- test/Unit/FieldDefinition/OptionalTest.php
- test/Unit/FieldDefinition/ReferenceTest.php
- test/Unit/FieldDefinition/ReferencesTest.php
- test/Unit/FieldResolution/CountResolution/BetweenMinimumAndMaximumCountTest.php
- test/Unit/FieldResolution/CountResolution/BetweenMinimumAndMaximumGreaterThanZeroCountTest.php
- test/Unit/FieldResolution/CountResolution/MinimumCountTest.php
- test/Unit/FieldResolution/FieldValueResolution/WithOptionalFieldValueTest.php
- test/Unit/FieldResolution/FieldValueResolution/WithOrWithoutOptionalFieldValueTest.php
- test/Unit/FieldResolution/FieldValueResolution/WithoutOptionalFieldValueTest.php
- test/Unit/FixtureFactory/UsingDefaultStrategyTest.php
- test/Unit/FixtureFactory/UsingWithOptionalStrategyTest.php
- test/Unit/FixtureFactory/UsingWithoutOptionalStrategyTest.php
- test/Unit/FixtureFactoryTest.php
> Fix: Rename strategies

- .github/settings.yml
- .github/workflows/integrate.yaml
- CHANGELOG.md
- composer.json
- composer.lock
> Added PHP 8.4 support

- .github/settings.yml
- .github/workflows/integrate.yaml
- CHANGELOG.md
- composer.json
- composer.lock
> Enhancement: Add support for PHP 8.5
